CREATE DATABASE Pessoas;

USE Pessoas;

CREATE TABLE Pessoa
(
	idPessoa	INT PRIMARY KEY IDENTITY
	,Nome		VARCHAR(200) NOT NULL
	,CPF		INT NOT NULL
	,RG			INT NOT NULL
	,DataNascimento		DATETIME NOT NULL
);

CREATE TABLE Email
(
	idEmail		INT PRIMARY KEY IDENTITY
	,idPessoa	INT FOREIGN KEY REFERENCES Pessoa(idPessoa)
	,Email		VARCHAR(200) NOT NULL
);

CREATE TABLE Telefone
(
	idTelefone	INT PRIMARY KEY  IDENTITY
	,idPessoa	INT FOREIGN KEY REFERENCES Pessoa(idPessoa)
	,Numero		INT NOT NULL
	,Operadora	VARCHAR(10) NOT NULL
	,Plano		VARCHAR(50) NOT NULL
);

CREATE TABLE CNH
(
	idCNH		INT PRIMARY KEY IDENTITY
	,idPessoa	INT FOREIGN KEY REFERENCES Pessoa(idPessoa)
	,Foto		IMAGE NOT NULL
	,NumeroRegistro		INT NOT NULL
	,Categoria	VARCHAR(10) NOT NULL
);
